#NAME: Marko Sevo
#EMAIL: marko.sevo7@gmail.com
#ID: 704833042

CC=gcc
files=lab2_list.c SortedList.h SortedList.c lab2b_list.csv lab2b_1.png lab2b_2.png lab2b_3.png lab2b_4.png lab2b_5.png profile.out lab2_list.gp Makefile README
.SILENT:

default:
	$(CC) -Wextra -Wall -g -lprofiler -pthread -o lab2_list lab2_list.c SortedList.c

tests: default
	rm lab2b_list.csv ; \
	./lab2_list --threads=1  --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=2  --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=4  --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=8  --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=24 --iterations=1000 --sync=m >> lab2b_list.csv
	./lab2_list --threads=1  --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=2  --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=4  --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=8  --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=1000 --sync=s >> lab2b_list.csv
	./lab2_list --threads=24 --iterations=1000 --sync=s >> lab2b_list.csv

	-./lab2_list --threads=1 --iterations=1 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=1 --iterations=2 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=1 --iterations=4 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=1 --iterations=8 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=1 --iterations=16 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=4 --iterations=1 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=4 --iterations=2 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=4 --iterations=4 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=4 --iterations=8 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=4 --iterations=16 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=8 --iterations=1 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=8 --iterations=2 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=8 --iterations=4 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=8 --iterations=8 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=8 --iterations=16 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=12 --iterations=1 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=12 --iterations=2 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=12 --iterations=4 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=12 --iterations=8 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=12 --iterations=16 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=16 --iterations=1 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=16 --iterations=2 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=16 --iterations=4 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=16 --iterations=8 --yield=id --lists=4 >> lab2b_list.csv
	-./lab2_list --threads=16 --iterations=16 --yield=id --lists=4 >> lab2b_list.csv

	./lab2_list --threads=1 --iterations=10 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=20 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=40 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=80 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=10 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=20 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=40 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=80 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=10 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=20 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=40 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=80 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=10 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=20 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=40 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=80 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=10 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=20 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=40 --yield=id --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=80 --yield=id --sync=m --lists=4 >> lab2b_list.csv

	./lab2_list --threads=1 --iterations=10 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=20 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=40 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=80 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=10 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=20 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=40 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=80 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=10 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=20 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=40 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=80 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=10 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=20 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=40 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=80 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=10 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=20 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=40 --yield=id --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=16 --iterations=80 --yield=id --sync=s --lists=4 >> lab2b_list.csv

	./lab2_list --threads=1 --iterations=1000 --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=1000 --sync=m --lists=8 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=1000 --sync=m --lists=16 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=m --lists=8 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=m --lists=16 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=m --lists=8 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=m --lists=16 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=m --lists=8 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=m --lists=16 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=m --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=m --lists=8 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=m --lists=16 >> lab2b_list.csv

	./lab2_list --threads=1 --iterations=1000 --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=1000 --sync=s --lists=8 >> lab2b_list.csv
	./lab2_list --threads=1 --iterations=1000 --sync=s --lists=16 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=s --lists=8 >> lab2b_list.csv
	./lab2_list --threads=2 --iterations=1000 --sync=s --lists=16 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=s --lists=8 >> lab2b_list.csv
	./lab2_list --threads=4 --iterations=1000 --sync=s --lists=16 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=s --lists=8 >> lab2b_list.csv
	./lab2_list --threads=8 --iterations=1000 --sync=s --lists=16 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=s --lists=4 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=s --lists=8 >> lab2b_list.csv
	./lab2_list --threads=12 --iterations=1000 --sync=s --lists=16 >> lab2b_list.csv

graphs: clean tests
	./lab2_list.gp

profile:
	CPUPROFILE=data.out ./lab2_list --threads=12 --iterations=1000 --sync=s
	pprof --text ./lab2_list data.out > profile.out
	pprof --list=threadFunc ./lab2_list data.out >> profile.out
	rm data.out

clean:
	rm -f lab2_list lab2b-704833042.tar.gz

dist: graphs
	tar -czf lab2b-704833042.tar.gz $(files)
